CREATE TABLE IF NOT EXISTS ORDERS (
  id IDENTITY PRIMARY KEY,
  note VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS AUDIT (
  id IDENTITY PRIMARY KEY,
  msg VARCHAR(200)
);

-- OUTBOX Table (simulating stored proc effect)
CREATE TABLE IF NOT EXISTS OUTBOX (
  id IDENTITY PRIMARY KEY,
  envelope_json CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
