name: SQLJ Translate & Commit

on:
  workflow_dispatch:         # Deutsch: Manuell startbar
  push:
    paths:
      - "sqlj-module-demo/src/main/sqlj/**"   # Deutsch: Modulpfad überwachen

permissions:
  contents: write            # Deutsch: Commit/Push erlauben

jobs:
  translate:
    runs-on: ubuntu-latest   # Deutsch: Standard-Runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Deutsch: vollständige Historie

      - name: Build custom translator image
        run: docker build -t sqlj-translator -f .github/sqlj-translator.Dockerfile .

      - name: Translate SQLJ in Docker (offline, kein Checker)
        run: |
          # Deutsch: Zielordner im Modul vorbereiten
          mkdir -p sqlj-module-demo/src/main/generated-sources/sqlj
          # Deutsch: Container mit eigenem Image starten – als root, EntryPoint überschreiben
          docker run --rm --user root --entrypoint /bin/bash -e LICENSE=accept -v "$PWD:/work" sqlj-translator -lc '
            set -e
            MOD="/work/sqlj-module-demo"
            OUT="$MOD/src/main/generated-sources/sqlj"
            SRC="$MOD/src/main/sqlj"
            mkdir -p "$OUT"
            if [ -d "$SRC" ]; then
              # Deutsch: Alle .sqlj-Dateien offline übersetzen
              find "$SRC" -name "*.sqlj" -print0 | \
              xargs -0 -I{} /opt/ibm/db2/V11.5/bin/sqlj \
                -d "$OUT" \
                -status -noChecker -profile db2 -collection APP "{}"
            else
              echo "Kein SQLJ-Verzeichnis gefunden: $SRC"
            fi
          '

      - name: Show changes
        run: git status --porcelain   # Deutsch: Änderungen anzeigen

      - name: Commit & Push if generated sources changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sqlj-module-demo/src/main/generated-sources/sqlj
            git commit -m "ci: SQLJ-Übersetzung -> Java (offline)"
            git push
          else
            echo "Keine Änderungen zum Commit."
          fi
