name: SQLJ Translate & Commit

on:
  workflow_dispatch:         # Deutsch: Manuelle Ausführung über die Actions-UI
  push:
    paths:
      - "sqlj-module-demo/src/main/generated-sources/sqlj/**"   # Deutsch: Bei Änderungen an .sqlj-Dateien automatisch starten

permissions:
  contents: write            # Deutsch: Erlaubt Commit/Push mit GITHUB_TOKEN

jobs:
  translate:
    runs-on: ubuntu-latest   # Deutsch: Standard-GitHub-Runner (Linux)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Deutsch: Vollständige Historie (saubere Commits)

      - name: Pull Db2 image (pinned)
        run: docker pull ibmcom/db2:11.5.8.0   # Deutsch: Fixe Version für reproduzierbare Builds

      - name: Translate SQLJ in Docker (offline, no checker)
        run: |
          # Deutsch: Zielordner vorbereiten
          mkdir -p src/sqlj-module-demo/main/generated-sources/sqlj
          # Deutsch: Container starten, EntryPoint überschreiben, Lizenz akzeptieren
          docker run --rm --entrypoint /bin/bash -e LICENSE=accept -v "$PWD:/work" ibmcom/db2:11.5.8.0 -lc '
            set -e
            mkdir -p /work/sqlj-module-demo/src/main/generated-sources/sqlj
            if [ -d /work/sqlj-module-demo/src/main/sqlj/osplus/syncdb2/sqlj ]; then
              # Deutsch: Alle .sqlj-Dateien offline (ohne DB-Checker) übersetzen
              find /work/sqlj-module-demo/src/main/sqlj/osplus/syncdb2/sqlj -name "*.sqlj" -print0 | \
              xargs -0 -I{} /opt/ibm/db2/V11.5/bin/sqlj \
                -d /work/sqlj-module-demo/src/main/generated-sources/sqlj \
                -status -noChecker -profile db2 -collection APP "{}"
            else
              echo "No sqlj-module-demo/src/main/sqlj/osplus/syncdb2/sqlj directory found; skipping."
            fi
          '

      - name: Show changes
        run: git status --porcelain   # Deutsch: Prüfen, ob generierte Dateien entstanden sind

      - name: Commit & Push if generated sources changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            # Deutsch: Commit-Author für CI setzen
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Deutsch: Nur generierte Quellen committen
            git add src/sqlj-module-demo/main/generated-sources/sqlj
            git commit -m "ci: translate SQLJ -> Java (offline)"
            git push
          else
            echo "No changes to commit."
          fi
